import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'
// import styles from '../styles/Home.module.css'


//below is client side rendering
export default function Home({results}) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1> Lets build HULU Clone</h1> */}
      {/* <h1>{API_KEY}</h1> */}
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  )
}

//server side rendering
export async function getServerSideProps(context){
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  // 'https://api.themoviedb.org/3/movie/550?api_key=f79c7096ecd5925933bccb1f7f6f753c'
  )
  .then((res) => res.json());
// // now accepts Props at Home Function
  return {
    props:{
     results: request.results,
        // request,
    },
  };
}
